<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title> | Apizr </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content=" | Apizr ">
      
      
      <link rel="icon" href="../../../resources/favicon.ico">
      <link rel="stylesheet" href="../../../public/docfx.min.css">
      <link rel="stylesheet" href="../../../public/main.css">
      <meta name="docfx:navrel" content="../../../toc.html">
      <meta name="docfx:tocrel" content="../../toc.html">
      
      <meta name="docfx:rel" content="../../../">
      
      
      <meta name="docfx:docurl" content="https://github.com/Respawnsive/Apizr/blob/dev/Apizr/Docs/Apizr.Docs/articles/legacy/v4/config_exceptions.md/#L1">
      <meta name="loc:inThisArticle" content="In this article">
      <meta name="loc:searchResultsCount" content="{count} results for &quot;{query}&quot;">
      <meta name="loc:searchNoResults" content="No results for &quot;{query}&quot;">
      <meta name="loc:tocFilter" content="Filter by title">
      <meta name="loc:nextArticle" content="Next">
      <meta name="loc:prevArticle" content="Previous">
      <meta name="loc:themeLight" content="Light">
      <meta name="loc:themeDark" content="Dark">
      <meta name="loc:themeAuto" content="Auto">
      <meta name="loc:changeTheme" content="Change theme">
      <meta name="loc:copy" content="Copy">
      <meta name="loc:downloadPdf" content="Download PDF">

      <script type="module" src="./../../../public/docfx.min.js"></script>

      <script>
        const theme = localStorage.getItem('theme') || 'auto'
        document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
      </script>

  </head>

  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../../../index.html">
            <img id="logo" class="svg" src="../../../resources/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
              <form class="search" role="search" id="search">
                <i class="bi bi-search"></i>
                <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
              </form>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="">

<h2 id="configuring-exception-handling">Configuring Exception handling</h2>
<h3 id="using-trycatch">Using <code>Try/Catch</code></h3>
<p>Here is an example of how to send a web request from an app - e.g. using Apizr in a Xamarin.Forms mobile app.</p>
<p>Inject <code>IApizrManager&lt;IYourDefinedInterface&gt;</code> where you need it - e.g. into your ViewModel constructor</p>
<pre><code class="lang-csharp">IList&lt;User&gt;? users;
try
{
    var userList = await _reqResManager.ExecuteAsync(api =&gt; api.GetUsersAsync());
    users = userList.Data;
}
catch (ApizrException&lt;UserList&gt; e)
{
    var message = e.InnerException is IOException ? &quot;No network&quot; : (e.Message ?? &quot;Error&quot;);
    UserDialogs.Instance.Toast(new ToastConfig(message) { BackgroundColor = Color.Red, MessageTextColor = Color.White });

    users = e.CachedResult?.Data;
}

if(users != null)
    Users = new ObservableCollection&lt;User&gt;(users);
</code></pre>
<p>We catch any ApizrException as it will contain the original inner exception, but also the previously cached result if some.
If you provided an IConnectivityHandler implementation and there's no network connectivity before sending request, Apizr will throw an IO inner exception without sending the request.</p>
<h3 id="using-actionexception-onexception">Using <code>Action&lt;Exception&gt; onException</code></h3>
<p>Instead of trycatching all the things, you may want to provide an exception handling action on call, thanks to <code>Action&lt;Exception&gt; onException</code> optional parameter.</p>
<p>Something like:</p>
<pre><code class="lang-csharp">reqResManager.ExecuteAsync(api =&gt; api.GetUsersAsync(), clearCache: false, onException: OnGetUsersException);

...

private void OnGetUsersException(Exception ex)
{
    ...
}
</code></pre>
<h3 id="using-optionalasync">Using <code>Optional.Async</code></h3>
<p>Here is how we could handle exceptions using Optional.Async:</p>
<pre><code class="lang-csharp">var optionalUserList = await _reqResOptionalMediator.SendFor(api =&gt; api.GetUsersAsync());

optionalPagedResult.Match(userList =&gt;
{
    if (userList.Data != null &amp;&amp; userList.Data.Any())
        Users = new ObservableCollection&lt;User&gt;(userList.Data);
}, e =&gt;
{
    var message = e.InnerException is IOException ? &quot;No network&quot; : (e.Message ?? &quot;Error&quot;);
    UserDialogs.Instance.Toast(new ToastConfig(message) { BackgroundColor = Color.Red, MessageTextColor = Color.White });

    if (e.CachedResult?.Data != null &amp;&amp; e.CachedResult.Data.Any())
        Users = new ObservableCollection&lt;User&gt;(e.CachedResult.Data);
});
</code></pre>
<p>Optional is pretty cool when trying to handle nullables and exceptions, but what if we still want to write it shorter to get our request done and managed with as less code as possible.
Even if we use the typed optional mediator or typed crud optional mediator to get things shorter, we still have to deal with the result matching boilerplate.
Fortunately, Apizr provides some dedicated extensions to help getting things as short as we can with exceptions handled.</p>
<h4 id="with-onresultasync">With <code>OnResultAsync</code></h4>
<p><code>OnResultAsync</code> ask you to provide one of these parameters:</p>
<ul>
<li><code>Action&lt;TResult&gt; onResult</code>: this action will be invoked just before throwing any exception that might have occurred during request execution
<pre><code class="lang-csharp">await _reqResOptionalMediator.SendFor(api =&gt; api.GetUsersAsync())
    .OnResultAsync(userList =&gt; 
    { 
        users = userList?.Data; 
    });
</code></pre>
</li>
<li><code>Func&lt;TResult, ApizrException&lt;TResult&gt;, bool&gt; onResult</code>: this function will be invoked with the returned result and potential occurred exception
<pre><code class="lang-csharp">await _reqResOptionalMediator.SendFor(api =&gt; api.GetUsersAsync())
    .OnResultAsync((userList, exception) =&gt; 
    { 
        users = userList?.Data; 

        if(exception != null)
            throw exception;

        return true;
    });
</code></pre>
</li>
<li><code>Func&lt;TResult, ApizrException&lt;TResult&gt;, Task&lt;bool&gt;&gt; onResult</code>: this function will be invoked async with the returned result and potential occurred exception
<pre><code class="lang-csharp">var success = await _reqResOptionalMediator.SendFor(api =&gt; api.GetUsersAsync())
    .OnResultAsync((userList, exception) =&gt; 
    { 
        users = userList?.Data; 

        return exception != null;
    });
</code></pre>
</li>
</ul>
<p>All give you a result returned from fetch if succeed, or cache if failed (if configured). The main goal here is to set any binded property with the returned result (fetched or cached), no matter of exceptions. Then the Action will let the exception throw, where the Func will let you decide to throw manually or return a success boolean flag.
Of course, remember to catch throwing exceptions.</p>
<h4 id="with-catchasync">With <code>CatchAsync</code></h4>
<p><code>CatchAsync</code> let you provide these parameters:</p>
<ul>
<li><code>Action&lt;Exception&gt; onException</code>: this action will be invoked just before returning the result from cache if fetch failed. Useful to inform the user of the api call failure and that data comes from cache.</li>
<li><code>letThrowOnExceptionWithEmptyCache</code>: True to let it throw the inner exception in case of empty cache, False to handle it with onException action and return empty cache result (default: False)</li>
</ul>
<p>This one returns result from fetch or cache (if configured), no matter of potential exception handled on the other side by an action callback</p>
<pre><code class="lang-csharp">var userList = await _reqResOptionalMediator.SendFor(api =&gt; api.GetUsersAsync())
    .CatchAsync(AsyncErrorHandler.HandleException, true);
</code></pre>
<p>Here we ask the api to get users and if it fails:</p>
<ul>
<li>There’s some cached data?
<ul>
<li><a href="https://github.com/Fody/AsyncErrorHandler">AsyncErrorHandler</a> will handle the exception like to inform the user that call just failed</li>
<li>Apizr will return the previous result from cache</li>
</ul>
</li>
<li>There’s no cached data yet!
<ul>
<li>letThrowOnExceptionWithEmptyCache is True? (which is the case here)
<ul>
<li>Apizr will throw the inner exception that will be catched further by AsyncErrorHander (this is its normal behavior)</li>
</ul>
</li>
<li>letThrowOnExceptionWithEmptyCache is False! (default)
<ul>
<li>Apizr will return the empty cache data (null) which has to be handled then</li>
</ul>
</li>
</ul>
</li>
</ul>
<p>One line of code to get all the thing done safely and shorter than ever!</p>

</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/Respawnsive/Apizr/blob/dev/Apizr/Docs/Apizr.Docs/articles/legacy/v4/config_exceptions.md/#L1" class="edit-link">Edit this page</a>
        </div>

        <div class="next-article d-print-none border-top" id="nextArticle"></div>

      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>

    <div class="container-xxl search-results" id="search-results"></div>

    <footer class="border-top text-secondary">
      <div class="container-xxl">
        <div class="flex-fill">
          Supported by Respawnsive
        </div>
      </div>
    </footer>
  </body>
</html>
